openapi: 3.0.0
info:
  title: Rengars statistics sevice
  description: This is a service for storing events from user and market place services
    and calculate statistics in time.
  contact:
    email: smitkva1@fel.cvut.cz
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://api.example.com/v1
tags:
- name: Statistics
  description: Everything about statistics.
paths:
  /UsersStatistics:
    get:
      tags:
      - Statistics
      summary: Gets global users statistics.
      operationId: get_users_statistics
      responses:
        "200":
          description: Data successfully obtained.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersStatistics'
        "400":
          description: General error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: The user not authorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Statistics
  /UsersStatistics/from/{from}/to/{to}:
    get:
      tags:
      - Statistics
      summary: Gets global users statistics of the period.
      operationId: get_users_statistics_period
      parameters:
      - name: from
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: to
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Data successfully obtained.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersStatistics'
        "400":
          description: General error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: The user not authorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Statistics
  /MarketplaceStatistics:
    get:
      tags:
      - Statistics
      summary: Gets global marketplace statistics.
      operationId: get_marketplace_statistics
      responses:
        "200":
          description: Data successfully obtained.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketplaceStatistics'
        "400":
          description: General error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: The user not authorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Statistics
  /MarketplaceStatistics/from/{from}/to/{to}:
    get:
      tags:
      - Statistics
      summary: Gets global marketplace statistics of the period.
      operationId: get_marketplace_statistics_period
      parameters:
      - name: from
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: to
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Data successfully obtained.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketplaceStatistics'
        "400":
          description: General error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: The user not authorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Statistics
  /HeadhunterStatistics:
    get:
      tags:
      - Statistics
      summary: Gets global headhunter statistics.
      operationId: get_headhunter_statistics
      responses:
        "200":
          description: Data successfully obtained.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeadhunterStatistics'
        "400":
          description: General error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: The user not authorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Statistics
  /HeadhunterStatistics/from/{from}/to/{to}:
    get:
      tags:
      - Statistics
      summary: Gets global headhunter statistics of the period.
      operationId: get_headhunter_statistics_period
      parameters:
      - name: from
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: to
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Data successfully obtained.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HeadhunterStatistics'
        "400":
          description: General error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: The user not authorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: General error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Statistics
components:
  schemas:
    UsersStatistics:
      type: object
      properties:
        ofPeriod:
          type: string
        eventTypesSum:
          type: array
          items:
            $ref: '#/components/schemas/UsersStatistics_eventTypesSum'
        usersSum:
          type: integer
          format: int32
        gendersSum:
          type: array
          items:
            $ref: '#/components/schemas/UsersStatistics_gendersSum'
        rolesSum:
          type: array
          items:
            $ref: '#/components/schemas/UsersStatistics_rolesSum'
      example:
        rolesSum:
        - sum: 5
          roleType: roleType
        - sum: 5
          roleType: roleType
        usersSum: 6
        eventTypesSum:
        - sum: 0
          eventType: eventType
        - sum: 0
          eventType: eventType
        gendersSum:
        - sum: 1
          genderType: genderType
        - sum: 1
          genderType: genderType
        ofPeriod: ofPeriod
    MarketplaceStatistics:
      type: object
      properties:
        ofPeriod:
          type: string
        eventTypesSum:
          type: array
          items:
            $ref: '#/components/schemas/UsersStatistics_eventTypesSum'
        offersSum:
          type: integer
          format: int32
        headhuntersSum:
          type: integer
          format: int32
        companiesSum:
          type: integer
          format: int32
      example:
        offersSum: 0
        companiesSum: 1
        eventTypesSum:
        - sum: 0
          eventType: eventType
        - sum: 0
          eventType: eventType
        ofPeriod: ofPeriod
        headhuntersSum: 6
    HeadhunterStatistics:
      type: object
      properties:
        ofPeriod:
          type: string
        offersSum:
          type: array
          items:
            $ref: '#/components/schemas/HeadhunterStatistics_offersSum'
      example:
        offersSum:
        - headhunterId: 0
          offersOpenSum: 6
          offersCloseSum: 1
        - headhunterId: 0
          offersOpenSum: 6
          offersCloseSum: 1
        ofPeriod: ofPeriod
    Error:
      required:
      - type
      type: object
      properties:
        type:
          type: string
          description: Unique id of the error
          example: errors.notifications.alreadySent
        message:
          type: string
          description: Error message
          example: Sent notification can not be cancelled.
        details:
          type: object
          description: Provides additional metadata about the error.
      description: "Describes error, its identifier and additional info."
    UsersStatistics_eventTypesSum:
      type: object
      properties:
        eventType:
          type: string
        sum:
          type: integer
          format: int32
      example:
        sum: 0
        eventType: eventType
    UsersStatistics_gendersSum:
      type: object
      properties:
        genderType:
          type: string
        sum:
          type: integer
          format: int32
      example:
        sum: 1
        genderType: genderType
    UsersStatistics_rolesSum:
      type: object
      properties:
        roleType:
          type: string
        sum:
          type: integer
          format: int32
      example:
        sum: 5
        roleType: roleType
    HeadhunterStatistics_offersSum:
      type: object
      properties:
        headhunterId:
          type: integer
          format: int32
        offersOpenSum:
          type: integer
          format: int32
        offersCloseSum:
          type: integer
          format: int32
      example:
        headhunterId: 0
        offersOpenSum: 6
        offersCloseSum: 1
